language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

before_script:
  - export APPLICATION_ENV=travis
  - composer install

script:
  - codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
  - wget https://raw.githubusercontent.com/delboy1978uk/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh

after_success:
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - ./send.sh failure $WEBHOOK_URL

notifications:
  irc: "irc.freenode.org#boneframework"
