language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

install:
  - composer install

script:
  - php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml