language: php

services:
  - docker

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

install:
  - docker-compose build
  - docker-compose up -d

before_script:
  - export APPLICATION_ENV=travis
  - docker-compose exec php /usr/bin/composer install

script:
  - docker-compose exec php vendor/bin/codecept run unit --coverage-xml --env travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

after_success:
  - wget https://raw.githubusercontent.com/delboy1978uk/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/delboy1978uk/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  irc: "irc.freenode.org#boneframework"
